services:
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl_certs:/etc/nginx/ssl_certs:ro
    depends_on:
      - app_cast_io
      - cast_io
      - castio_au
      - castio_ca
      - castio_cn
      - castio_uk
      - castio_us
    networks:
      - app-network

networks:
  app-network:
    driver: bridge