services:
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl_certs:/etc/nginx/ssl_certs:ro
    depends_on:
      - app_cast_io
      - cast_io
      - castio_au
      - castio_cn
      - castio_uk
      - castio_us
    networks:
      - app-network

  app_cast_io:
    build: ./app_cast_io
    container_name: app_cast_io
    expose:
      - "80"
    env_file:
      - ./app_cast_io/.env
    networks:
      app-network:
        aliases:
          - app.cast.io

  cast_io:
    build: ./cast_io
    container_name: cast_io
    expose:
      - "80"
    env_file:
      - ./cast_io/.env
    networks:
      app-network:
        aliases:
          - cast.io

  castio_au:
    build: ./castio_au
    container_name: castio_au
    expose:
      - "80"
    env_file:
      - ./castio_au/.env
    networks:
      app-network:
        aliases:
          - castio.au

  castio_cn:
    build: ./castio_cn
    container_name: castio_cn
    expose:
      - "80"
    env_file:
      - ./castio_cn/.env
    networks:
      app-network:
        aliases:
          - castio.cn

  castio_uk:
    build: ./castio_uk
    container_name: castio_uk
    expose:
      - "80"
    env_file:
      - ./castio_uk/.env
    networks:
      app-network:
        aliases:
          - castio.uk

  castio_us:
    build: ./castio_us
    container_name: castio_us
    expose:
      - "80"
    env_file:
      - ./castio_us/.env
    networks:
      app-network:
        aliases:
          - castio.us

networks:
  app-network:
    driver: bridge